apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuln-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln-spring
  template:
    metadata:
      labels:
        app: vuln-spring
        version: v1
    spec:
      containers:
        - image: 10.0.0.180:5000/vuln-spring
          name: vuln-spring
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always